### ISSUE TITLE
1.12.2 my chest are black. biomes o plenty and quark color chest and dark oak chest are gray 

### ISSUE THREAD

**Issue by andrewq99** [SmileycorpMC/Cosmetic-Wood#9]
![a](https://github.com/SmileycorpMC/Cosmetic-Wood/assets/39251943/81e713ef-7ee0-4777-b990-1371ae20b19c)

**Comment by SmileycorpMC** [comment]
What other mods do you have installed?

**Comment by andrewq99** [comment]
![a](https://github.com/SmileycorpMC/Cosmetic-Wood/assets/39251943/c0c4cde6-809f-4598-a8d9-c8ae5acc0249)

**Comment by andrewq99** [comment]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-11-30 00:50:12 EST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.minecraft.tileentity.TileEntityChest cannot be cast to net.smileycorp.cosmeticwood.plugins.vanilla.tileentity.TileCWChest
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: net.minecraft.tileentity.TileEntityChest cannot be cast to net.smileycorp.cosmeticwood.plugins.vanilla.tileentity.TileCWChest
    at net.smileycorp.cosmeticwood.plugins.vanilla.tileentity.TileCWChest.isChestAt(TileCWChest.java:83)
    at net.smileycorp.cosmeticwood.plugins.vanilla.tileentity.TileCWChest.getAdjacentChest(TileCWChest.java:67)
    at net.minecraft.tileentity.TileEntityChest.checkForAdjacentChests(TileEntityChest.java:173)
    at net.smileycorp.cosmeticwood.plugins.vanilla.tileentity.TileCWChest.checkForAdjacentChests(TileCWChest.java:59)
    at net.smileycorp.cosmeticwood.plugins.vanilla.tileentity.TileCWChest.setType(TileCWChest.java:49)
    at net.smileycorp.cosmeticwood.common.block.WoodBlock.onBlockPlacedBy(WoodBlock.java:90)
    at net.smileycorp.cosmeticwood.plugins.vanilla.block.BlockCWChest.onBlockPlacedBy(BlockCWChest.java:95)
    at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:186)
    at net.smileycorp.cosmeticwood.plugins.vanilla.item.ItemBlockChestCW.onItemUse(ItemBlockChestCW.java:62)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889)
    at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:186)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:492)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 863854072 bytes (823 MB) / 2348810240 bytes (2240 MB) up to 5368709120 bytes (5120 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 89
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 57 mods loaded, 57 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                   | Version                  | Source                                          | Signature                                |
       |:------ |:-------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                                   | None                                     |
       | LCHIJA | mcp                  | 9.42                     | minecraft.jar                                   | None                                     |
       | LCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2860.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                | 14.23.5.2860             | forge-1.12.2-14.23.5.2860.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | xaerominimap_core    | 1.12.2-1.0               | minecraft.jar                                   | None                                     |
       | LCHIJA | xaeroworldmap_core   | 1.12.2-1.0               | minecraft.jar                                   | None                                     |
       | LCHIJA | foamfixcore          | 7.7.4                    | minecraft.jar                                   | None                                     |
       | LCHIJA | animalnet            | v1.12.2 b3               | animalnet-v1.12.2+b3.jar                        | None                                     |
       | LCHIJA | crafttweaker         | 4.1.20                   | CraftTweaker2-1.12-4.1.20.689.jar               | None                                     |
       | LCHIJA | jei                  | 4.16.1.302               | jei_1.12.2-4.16.1.302.jar                       | None                                     |
       | LCHIJA | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
       | LCHIJA | atlaslib             | 1.1.6                    | Atlas-Lib-1.12.2-1.1.6.jar                      | None                                     |
       | LCHIJA | quark                | r1.6-179                 | Quark-r1.6-179.jar                              | None                                     |
       | LCHIJA | autoreglib           | 1.3-32                   | AutoRegLib-1.3-32.jar                           | None                                     |
       | LCHIJA | thebombzenapi        | 2.9.3                    | ThebombzenAPI-v2.9.3-mc1.12.2.jar               | None                                     |
       | LCHIJA | autoswitch           | 5.6.2                    | AutoSwitch-v5.6.2-mc1.12.2.jar                  | None                                     |
       | LCHIJA | badmobs              | 1.1.40                   | BadMobs-1.12.2-1.1.40.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | biomesoplenty        | 7.0.1.2445               | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar   | None                                     |
       | LCHIJA | birdsfoods           | 3.1 - [1.12]             | birdsfoods-1.12+-+3.1.jar                       | None                                     |
       | LCHIJA | blockcraftery        | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                  | None                                     |
       | LCHIJA | buildinggadgets      | 2.8.4                    | BuildingGadgets-2.8.4.jar                       | None                                     |
       | LCHIJA | colored_wood_mod     | 1.6.1                    | Colored_Wood_Mod_v1.6.1.jar                     | None                                     |
       | LCHIJA | connectedglass       | 1.1.2                    | connectedglass-1.1.2-mc1.12.jar                 | None                                     |
       | LCHIJA | cookingforblockheads | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar           | None                                     |
       | LCHIJA | cosmeticwood         | 1.1.2                    | Cosmetic-Wood-1.12.2-1.1.2.jar                  | None                                     |
       | LCHIJA | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.20.689.jar               | None                                     |
       | LCHIJA | crafttweakerjei      | 2.0.3                    | CraftTweaker2-1.12-4.1.20.689.jar               | None                                     |
       | LCHIJA | customnpcs           | 1.12                     | CustomNPCs_1.12.2-(05Jul20).jar                 | None                                     |
       | LCHIJA | deadwood             | 1.1                      | DeadWood-1.1.jar                                | None                                     |
       | LCHIJA | durabilityviewer     | 1.6                      | DurabilityViewer-1.12-forge14.21.1.2387-1.6.jar | None                                     |
       | LCHIJA | eggs                 | 1.0                      | EM3R50N-EatTheEggs-1.12.2-14.23.4.2760.jar      | None                                     |
       | LCHIJA | esrainplants         | 1.0.0                    | FarmingInRain-1.0.0.jar                         | None                                     |
       | LCHIJA | fastleafdecay        | v14                      | FastLeafDecay-v14.jar                           | None                                     |
       | LCHIJA | foamfix              | 0.10.14-1.12.2           | foamfix-0.10.14-1.12.2.jar                      | None                                     |
       | LCHIJA | cfm                  | 6.3.0                    | furniture-6.3.2-1.12.2.jar                      | None                                     |
       | LCHIJA | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | journeymap           | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                     | None                                     |
       | LCHIJA | keywizard            | 1.12.2-1.7.3             | keywizard-1.12.2-1.7.3.jar                      | None                                     |
       | LCHIJA | mapwriter            | 2.8.2                    | MapWriter-1.12.2-2.8.2.jar                      | None                                     |
       | LCHIJA | mod_autofish         | 1.12-1.7                 | mod_autofish_forge-1.12-1.7.jar                 | None                                     |
       | LCHIJA | offlineskins         | 1.12.2-v6                | OfflineSkins-1.12.2-v6.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | oreexcavation        | 1.4.150                  | OreExcavation-1.4.150.jar                       | None                                     |
       | LCHIJA | getalltheseeds       | 1.12a                    | Pam's+Get+all+the+Seeds!+1.12a.jar              | None                                     |
       | LCHIJA | harvestcraft         | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zg.jar                 | None                                     |
       | LCHIJA | pizzacraft           | 2.0.19                   | PizzaCraft-1.12.2-2.0.19.jar                    | None                                     |
       | LCHIJA | seedprotect          | 1.2.0                    | seedprotect-1.12.2-1.2.0.jar                    | None                                     |
       | LCHIJA | theoneprobe          | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                     | None                                     |
       | LCHIJA | ts2k16               | 1.2.10                   | TS2K16-1.2.10.jar                               | None                                     |
       | LCHIJA | vanillafix           | 1.0.10-150               | VanillaFix-1.0.10-150.jar                       | None                                     |
       | LCHIJA | veinminer            | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
       | LCHIJA | veinminermodsupport  | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
       | LCHIJA | xaerominimap         | 24.6.1                   | Xaeros_Minimap_24.6.1_Forge_1.12.jar            | None                                     |
       | LCHIJA | xaeroworldmap        | 1.39.0                   | XaerosWorldMap_1.39.0_Forge_1.12.jar            | None                                     |
       | LCHIJA | xlfoodmod            | 1.12.2-1.9.2             | XL-Food-Mod-1.12.2-1.9.2.jar                    | None                                     |
       | LCHIJA | zevac.survivalflight | 0.1.11                   | Zevac.SurvivalFlight_1.12.x-0.1.11.jar          | None                                     |
       | LCHIJA | mysticallib          | 1.12.2-1.13.0            | mysticallib-1.12.2-1.13.0.jar                   | None                                     |
       | LCHIJA | osv                  | 5.14                     | Ore+Stone+Variants-5.14.jar                     | None                                     |
  Loaded coremods (and transformers): Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      offlineskins (OfflineSkins-1.12.2-v6-core.jar)
                                        lain.mods.skins.init.forge.asm.ASMTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      XaeroMinimapPlugin (Xaeros_Minimap_24.6.1_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerMPTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                        xaero.common.core.transformer.SaveFormatTransformer
                                        xaero.common.core.transformer.GuiIngameForgeTransformer
                                        xaero.common.core.transformer.MinecraftServerTransformer
                                        xaero.common.core.transformer.GuiBossOverlayTransformer
                                        xaero.common.core.transformer.ModelRendererTransformer
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.39.0_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.EntityPlayerMPTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                        xaero.map.core.transformer.SaveFormatTransformer
                                        xaero.map.core.transformer.BiomeColorHelperTransformer
                                        xaero.map.core.transformer.MinecraftServerTransformer
                                        xaero.map.core.transformer.MinecraftTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: Cosmetic Wood (cosmeticwood)
